services:
  redis:
    image: redislabs/redisearch:2.2.4
    restart: unless-stopped

  falcosidekick-ui:
    image: falcosecurity/falcosidekick-ui:v2.0.2
    command: -r redis:6379 
    ports:
      - "127.0.5.1:2802:2802"
    depends_on:
      - redis
    restart: unless-stopped

  falcosidekick:
    image: falcosecurity/falcosidekick:2.26.0
    environment:
      - WEBUI_URL=http://falcosidekick-ui:2802
    ports:
      - "127.0.5.1:2801:2801"
    depends_on:
      - falcosidekick-ui
    restart: unless-stopped

